# Generated by Django 5.2.2 on 2025-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domisilipengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='domisiliusaha',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='pindahdatang',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sktmpengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='skupengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratkematian',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=10),
        ),
        migrations.AlterField(
            model_name='suratkkpengantar',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratktpbarupengantar',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
    ]
