# Generated by Django 5.2.2 on 2025-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0002_alter_domisilipengajuan_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanLainnya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=25)),
                ('no_whatsapp', models.CharField(max_length=15, verbose_name='No. WhatsApp')),
                ('jenis_pengajuan', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='pengajuan_lainnya/')),
                ('status', models.CharField(choices=[], default='diajukan', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('hasil_surat', models.FileField(blank=True, null=True, upload_to='pengajuan_lainnya/hasil/')),
            ],
        ),
    ]
