# Generated by Django 5.2.2 on 2025-06-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0003_pengajuanlainnya'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuanlainnya',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pengajuanlainnya',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
