# Generated by Django 5.2.2 on 2025-06-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0006_suratlainnya_delete_pengajuanlainnya'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratlainnya',
            name='jenis_pengajuan',
            field=models.CharField(default='Surat Lainnya', max_length=100),
        ),
        migrations.AlterField(
            model_name='suratlainnya',
            name='nik',
            field=models.CharField(max_length=20),
        ),
    ]
