# Generated by Django 5.2.6 on 2026-08-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0007_suratlainnya_jenis_pengajuan_alter_suratlainnya_nik'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='profil_desa/', verbose_name='Foto Kantor Desa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto Kantor Desa',
                'verbose_name_plural': 'Foto Kantor Desa',
            },
        ),
    ]
