# Generated by Django 5.2.6 on 2026-08-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0008_profildesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='struktur_organisasi/')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Struktur Organisasi',
                'verbose_name_plural': 'Struktur Organisasi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='TentangDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sejarah_singkat', models.TextField(help_text='Cerita asal-usul nama desa, sejarah singkat, dll.')),
                ('potensi_kearifan_lokal', models.TextField(help_text='Potensi alam, sosial-budaya, ekonomi desa.')),
                ('lokasi_embed_url', models.URLField(blank=True, help_text='Ambil dari Google Maps > Bagikan > Sematkan peta > copy URL di dalam src="..."', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tentang Desa',
                'verbose_name_plural': 'Tentang Desa',
            },
        ),
        migrations.CreateModel(
            name='MisiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('tentang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misi_items', to='kembang.tentangdesa')),
            ],
            options={
                'verbose_name': 'Poin Misi',
                'verbose_name_plural': 'Poin Misi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='VisiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('tentang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visi_items', to='kembang.tentangdesa')),
            ],
            options={
                'verbose_name': 'Poin Visi',
                'verbose_name_plural': 'Poin Visi',
                'ordering': ['urutan'],
            },
        ),
    ]
