# Generated by Django 5.2.6 on 2026-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0009_strukturorganisasi_tentangdesa_misiitem_visiitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentangdesa',
            name='lokasi_embed_url',
            field=models.URLField(blank=True, help_text='Paste link share dari Google Maps (klik tombol Bagikan di Maps, copy link-nya). Contoh: https://maps.app.goo.gl/xxxxxxx', null=True),
        ),
    ]
