# Generated by Django 5.2.6 on 2026-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0010_alter_tentangdesa_lokasi_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangdesa',
            name='lokasi_embed_cache',
            field=models.URLField(blank=True, editable=False, help_text='Auto-generated dari lokasi_embed_url, jangan diedit manual.', null=True),
        ),
    ]
