# Generated by Django 5.2.6 on 2026-08-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0011_tentangdesa_lokasi_embed_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratlainnya',
            name='alamat_lengkap',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='suratlainnya',
            name='keterangan',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='suratlainnya',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
    ]
