# Generated by Django 5.2.6 on 2026-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0012_alter_suratlainnya_alamat_lengkap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strukturorganisasi',
            options={'ordering': ['level', 'urutan'], 'verbose_name': 'Struktur Organisasi', 'verbose_name_plural': 'Struktur Organisasi'},
        ),
        migrations.AddField(
            model_name='strukturorganisasi',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pimpinan (Kepala Desa)'), (2, 'Perangkat Inti (Sekretaris/Bendahara)'), (3, 'Staf (Kaur/Kasi/Kadus)')], default=3),
        ),
    ]
