# Generated by Django 5.2.6 on 2026-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0013_alter_strukturorganisasi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strukturorganisasi',
            options={'ordering': ['slot', 'urutan'], 'verbose_name': 'Struktur Organisasi', 'verbose_name_plural': 'Struktur Organisasi'},
        ),
        migrations.RemoveField(
            model_name='strukturorganisasi',
            name='level',
        ),
        migrations.AddField(
            model_name='strukturorganisasi',
            name='slot',
            field=models.CharField(choices=[('bpd', 'B.P.D'), ('kepala_desa', 'Kepala Desa'), ('sekretaris_desa', 'Sekretaris Desa'), ('kaur_pemerintahan', 'Kaur Pemerintahan'), ('kaur_ekbang', 'Kaur Ekbang'), ('kaur_prolap', 'Kaur Prolap'), ('kaur_kesra', 'Kaur Kesra'), ('kaur_keuangan', 'Kaur Keuangan'), ('kaur_umum', 'Kaur Umum'), ('pelaksana_teknis', 'Pelaksana Teknis Lapangan'), ('unsur_kewilayahan', 'Unsur Kewilayahan')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
