# Generated by Django 5.2.6 on 2026-09-01 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0014_alter_strukturorganisasi_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesaEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_jwk', models.TextField(help_text='JWK public key RSA-OAEP, format JSON.')),
                ('wrapped_private_key', models.TextField(help_text='JSON: {ciphertext, iv, salt, iterations} — private key terenkripsi passphrase kantor.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunci Enkripsi Kantor Desa',
                'verbose_name_plural': 'Kunci Enkripsi Kantor Desa',
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField(help_text='AES-GCM ciphertext, base64.')),
                ('iv', models.CharField(help_text='IV AES-GCM (12 byte), base64.', max_length=32)),
                ('wrapped_key_warga', models.TextField(help_text='AES key dibungkus public key warga, base64.')),
                ('wrapped_key_desa', models.TextField(help_text='AES key dibungkus public key Kantor Desa, base64.')),
                ('dibaca_staff', models.BooleanField(default=False)),
                ('dibaca_warga', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='kembang.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_jwk', models.TextField(help_text='JWK public key RSA-OAEP milik warga, format JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
