# Generated by Django 5.2.6 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0015_desaencryptionkey_chatthread_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desaencryptionkey',
            name='wrapped_private_key_recovery',
            field=models.TextField(default=1, help_text='JSON: {ciphertext, iv, salt, iterations} — private key terenkripsi kode pemulihan kantor.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desaencryptionkey',
            name='wrapped_private_key',
            field=models.TextField(help_text='JSON: {ciphertext, iv, salt, iterations} — private key terenkripsi passphrase harian kantor.'),
        ),
    ]
