# Generated by Django 5.2.6 on 2026-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0016_desaencryptionkey_wrapped_private_key_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='staff_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='warga_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
