# Generated by Django 5.2.6 on 2026-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0017_chatthread_staff_typing_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strukturorganisasi',
            name='slot',
            field=models.CharField(choices=[('bpd', 'B.P.D'), ('kepala_desa', 'Kepala Desa'), ('sekretaris_desa', 'Sekretaris Desa'), ('kasi_pemerintahan', 'Kasi Pemerintahan'), ('kasi_kesejahteraan', 'Kasi Kesejahteraan'), ('kasi_pelayanan', 'Kasi Pelayanan'), ('kaur_tatausahadannumum', 'Kaur Tata Usaha dan Umum'), ('kaur_keuangan', 'Kaur Keuangan'), ('kaur_perencanaan', 'Kaur Perencanaan'), ('kepala_wilayah', 'Kepala Dusun')], max_length=30),
        ),
    ]
