# Generated by Django 5.2.6 on 2026-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0018_alter_strukturorganisasi_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domisilipengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='domisiliusaha',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='pindahdatang',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='sktmpengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='skupengajuan',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratkelahiran',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratkematian',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=10),
        ),
        migrations.AlterField(
            model_name='suratkkpengantar',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratktpbarupengantar',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratlainnya',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Sedang Diproses'), ('ditolak', 'Ditolak'), ('selesai', 'Sudah Diproses')], default='diajukan', max_length=20),
        ),
    ]
