# Generated by Django 5.2.6 on 2026-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0019_alter_domisilipengajuan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentangdesa',
            name='no_whatsapp',
            field=models.CharField(default=1, max_length=15, verbose_name='No. WhatsApp'),
            preserve_default=False,
        ),
    ]
