# Generated by Django 5.2.6 on 2026-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kembang', '0020_tentangdesa_no_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='domisilipengajuan',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='domisiliusaha',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='pindahdatang',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='sktmpengajuan',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='skupengajuan',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='suratkelahiran',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='suratkematian',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='suratkkpengantar',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='suratktpbarupengantar',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='suratlainnya',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='no_whatsapp',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='No. WhatsApp'),
        ),
    ]
